Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/AbcSize:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - db/**/*

Layout/LineLength:
  Max: 170
  Exclude:
    - db/**/*
